version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    links:
      - redis
  redis:
    image: redis:5
    ports:
      - "6379:6379"
